### ISSUE TITLE
Default JWT depracted call issue

### ISSUE THREAD

**Issue by mikehhhhhhh** [adonisjs/adonis-fullstack-app#17]
I came across this in my app. The secret seems to be set to `'self::app.appKey'`

Should this be `Env.get('APP_KEY')` ?

https://github.com/adonisjs/adonis-fullstack-app/blob/develop/config/auth.js#L72

**Comment by RomainLanz** [comment]
Hey @mikehhhhhhh!

It's not a security issue at all.
Could you please made a PR to use `Env` instead?
https://github.com/adonisjs/adonis-auth/pull/90/files
