### ISSUE TITLE
How do I convert ES6 codes to ES5?

### ISSUE THREAD

**Issue by emirhanengn** [adonisjs/adonis-fullstack-app#20]
Hello!

Me again! :D

When writing ES6 codes, how can we convert them to ES5 code?
I searched, but I didn't get a proper result.

Thanks!

**Comment by RomainLanz** [comment]
Hey @emirhanengn! 👋 

Please, use the Discord Server or the forum to ask this kind of question.

Also, you don't need to transpile Adonis code to ES5. Node.js handle ESNext syntax.
