### ISSUE TITLE
Could you add a **mongo** branch?

### ISSUE THREAD

**Issue by wxs77577** [adonisjs/adonis-fullstack-app#32]
I've create [a boilerplate of mongodb](https://github.com/topfullstack/adonis-fullstack-app/tree/mongo), and people can use it via 

```bash
adonis new --blueprint=adonisjs/adonis-fullstack-app --branch=mongo yardstick
```

I want to make it easier, could you add a `mongo` branch so that I can push it?`

And then, people can use it via 

```bash
adonis new --branch=mongo yardstick`
```

**Comment by wxs77577** [comment]
I think use  `adonis new --branch=mongo yardstick` is the easiest way.

**Comment by thetutlage** [comment]
I believe passing a github repo is usually easy. Adding it to the AdonisJs org gives the impression, that this is maintained officially and not by the community.
